### ISSUE TITLE
La page 404 est maquettée

### ISSUE THREAD

**Issue by clemenceprem** [Kozea/www-pellov#4]
J'en ai pas pour PM. Qui qui s'y colle ? @piline @annabellou @hugobernard

**Comment by annabellou** [comment]
C'est moi je prends

**Comment by clemenceprem** [comment]
Joie éternelle

**Comment by annabellou** [comment]
https://drive.google.com/open?id=1tr_ixQB1ow4-lvnwDtJdtnHlKSUcc7va

**Comment by annabellou** [comment]
Le lien a l'air cassé...
![promomaker-maquettes-web-page-404](https://user-images.githubusercontent.com/7512422/32939682-99aee696-cb80-11e7-9e67-514d2def3570.png)
