### ISSUE TITLE
Le site marche même si on a pas un écran 4k

### ISSUE THREAD

**Issue by paradoxxxzero** [Kozea/www-pellov#8]
![image](https://user-images.githubusercontent.com/271144/33167026-8b464a02-d03c-11e7-9ae4-46718feea97a.png)

**Comment by liZe** [comment]
Les gens qui ont eu l'outrecuidance d'utiliser du SVG pour faire ça n'ont qu'à payer pour leur témérité.

Plus sérieusement : c'était le deal d'accepter les erreurs de conception comme celles-là.

**Comment by paradoxxxzero** [comment]
Bon ok mais au moins corriger le fait que la vidéo youtube casse le layout en mobile
![screenshot_20180427-000139](https://user-images.githubusercontent.com/271144/39334291-536b04f6-49ae-11e8-856f-91fff8a319f4.jpg)

**Comment by paradoxxxzero** [comment]
Si jamais quelqu'un a envie que le bug du début soit corrigé, il suffit de mettre `font-size: 80px` sur le style du text du svg.
